#!/usr/bin/env node
// docs/ablations.md from bench/out/ablate-*.json: table + inline SVG bars (no plotting library).
//   node bench/ablate-report.mjs [--readout dna02]
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { ROOT } from './lib/graph.mjs';
const arg = (k, d) => { const i = process.argv.indexOf('--' + k); return i > 0 ? process.argv[i + 1] : d; };
const READOUT = arg('readout', 'dng02'), TAG = arg('tag', ''), OUT = arg('out', TAG ? `docs/ablations${TAG}.md` : 'docs/ablations.md');
const r = JSON.parse(readFileSync(join(ROOT, `bench/out/ablate-${READOUT}${TAG}.json`), 'utf8'));
const names = Object.keys(r.conditions);
const bar = (title, key, unit, absolute = false) => {
  const vals = names.map((n) => (absolute ? Math.abs(r.conditions[n][key]) : r.conditions[n][key]));
  const max = Math.max(1e-6, ...vals), w = 520, h = 22 * names.length + 30, lab = 170;
  let s = `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" font-family="ui-monospace, monospace" font-size="12">`;
  s += `<text x="4" y="14" font-weight="bold">${title}</text>`;
  names.forEach((n, i) => { const y = 26 + i * 22, bw = ((w - lab - 60) * vals[i]) / max; s += `<text x="4" y="${y + 13}">${n}</text><rect x="${lab}" y="${y}" width="${bw.toFixed(1)}" height="16" fill="#4c8dff"/><text x="${(lab + bw + 4).toFixed(1)}" y="${y + 13}">${vals[i]} ${unit}</text>`; });
  return s + '</svg>';
};
const svg = (name, body) => { writeFileSync(join(ROOT, `docs/ablations${TAG}-${name}.svg`), body); return `![${name}](ablations${TAG}-${name}.svg)`; };
let md = `# Ablations\n\nPillar-course cruise (${r.seconds} s, base amplitude 0.7) under each condition. Readout: **${READOUT}**${READOUT === 'dna02' ? ' (deviation from the plan, see DECISIONS.md: the DNg02 code does not steer in this LIF)' : ''}; bridge gain 2, DNg02 tonic ${r.dnBias} mV/ms, turn gain ${r.turnGain}, haltere proxy sign ${r.haltereSign} (docs/phase5.md; docs/followups.md §2 on what it really does)${r.gate ? `; **readout gate on** (a silent pair commands nothing) and rest re-centring τ ${r.recenterTau || 0} s (docs/followups.md §3)` : ''}. Generated by \`bench/ablate-report.mjs\` from \`bench/out/ablate-${READOUT}${TAG}.json\`.\n\n`;
md += `| condition | collisions | heading drift | max excursion | wobble (yaw-rate sd) | distance | DNg02 L/R | DNa02 L/R | wing MN L/R | spikes/frame | muted |\n| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |\n`;
for (const n of names) { const c = r.conditions[n]; md += `| ${n} | ${c.collisions} | ${c.driftDeg}° | ${c.maxExcursionDeg}° | ${c.wobbleRadS} rad/s | ${c.distance} | ${c.dng02.join(' / ')} | ${c.dna02.join(' / ')} | ${c.wingMn.join(' / ')} | ${c.spikesPerFrame} | ${c.muted ?? 0} |\n`; }
md += `\n${svg('collisions', bar('collisions', 'collisions', ''))}\n\n${svg('drift', bar('|heading drift|, degrees', 'driftDeg', '°', true))}\n\n${svg('wobble', bar('wobble: yaw-rate sd, rad/s', 'wobbleRadS', 'rad/s'))}\n\n${svg('spikes', bar('[B] spikes per 16.7 ms frame', 'spikesPerFrame', ''))}\n`;
md += `\n## Conditions\n\n- **intact**: bridge on, haltere proxy on.\n- **bridge-off**: [B] gets no visual input (its own photoreceptors are dead; the null).\n- **recurrence-off**: Xenova's \`silenced\` flag: spikes are recorded but never delivered.\n- **central-brain-silenced**: every \`cb_*\` superclass neuron held below threshold (only optic lobe, descending neurons and VNC live).\n- **haltere-off**: no yaw-rate current on the 205 haltere afferents.\n- **neck-cut**: all descending neurons held below threshold (brain → VNC edges carry nothing).\n- **decapitated**: the whole brain (central, optic, visual projection, descending) held below threshold; the VNC alone.\n\nMuting is a −50 mV/ms current through the inject path, not an edge deletion: the cells exist, cannot fire, and their incoming synapses still count toward nothing.\n`;
md += `\n## Reading the table\n\n`;
const c = r.conditions, has = (n) => c[n] !== undefined;
if (has('intact') && has('bridge-off')) md += `- **Vision matters.** Bridge off is the null: the same fly with no visual input drifts ${c['bridge-off'].driftDeg}° against ${c.intact.driftDeg}° intact, with the same collisions (${c['bridge-off'].collisions} vs ${c.intact.collisions}) over ${r.seconds} s.\n`;
if (has('intact') && has('haltere-off')) md += `- **The haltere proxy is the stabiliser.** Without it the drift is ${c['haltere-off'].driftDeg}° and the wobble ${c['haltere-off'].wobbleRadS} rad/s, against ${c.intact.driftDeg}° and ${c.intact.wobbleRadS} rad/s.\n`;
const silent = names.filter((n) => c[n].dna02[0] + c[n].dna02[1] < 0.5);
if (silent.length) md += `- **Silent readout populations spin the fly, and that is the readout, not the biology.** In ${silent.join(', ')} the readout populations are (near) silent, so the rest-subtracted command saturates at the maximum turn and the trajectory is the same in each (${c[silent[0]].driftDeg}°). For those conditions the substantive result is the rates: `;
if (silent.length) md += silent.map((n) => `${n}: DNg02 ${c[n].dng02.join('/')}, DNa02 ${c[n].dna02.join('/')}, wing MN ${c[n].wingMn.join('/')} Hz`).join('; ') + '.\n';
if (has('recurrence-off')) md += `- **Recurrence off** leaves only what is injected: DNg02 at its tonic rate (${c['recurrence-off'].dng02.join('/')} Hz), everything downstream silent (wing MN ${c['recurrence-off'].wingMn.join('/')} Hz). The VNC produces nothing from descending drive alone without transmission.\n`;
if (has('neck-cut') && has('decapitated')) md += `- **Neck cut and decapitated look alike:** the wing motor neurons keep firing at ${c['neck-cut'].wingMn.join('/')} and ${c.decapitated.wingMn.join('/')} Hz from the VNC's own input (the haltere afferents enter the VNC directly), so the VNC does hold activity without the brain, but it is a driven response, not a demonstrated central pattern generator.\n`;
if (has('central-brain-silenced')) md += `- **Central brain silenced** (${c['central-brain-silenced'].muted} cells) still leaves the optic lobe → descending → VNC path: wing MN ${c['central-brain-silenced'].wingMn.join('/')} Hz, DNa02 ${c['central-brain-silenced'].dna02.join('/')} Hz; the reflex-only fly has a weaker, still lateralised drive.\n`;
const totalColl = names.reduce((a, n) => a + c[n].collisions, 0);
md += totalColl ? `- Collisions over ${r.seconds} s: ${names.map((n) => `${n} ${c[n].collisions}`).join(', ')}.\n` : `- All runs: zero collisions over ${r.seconds} s on this course at 0.77 units/s; collisions never discriminated between conditions at this length.\n`;
writeFileSync(join(ROOT, OUT), md);
console.log(`wrote ${OUT} and 4 SVGs`);
