#!/usr/bin/env bash
# Regenerate nix/assets.nix: fixed-output fetchurl derivations for every large data asset,
# with the SHA-256 git-lfs already verified (the LFS oid *is* the SHA-256 of the content) and
# the MaleCNS annotation table's SHA-256 from Xenova's manifest. Pinned to the submodule commits.
set -euo pipefail
cd "$(dirname "$0")/.."
XREV=$(git -C vendor/fruit-fly-simulation rev-parse HEAD)
AREV=$(git -C vendor/fruit-fly-brain rev-parse HEAD)
ANN_URL=$(python3 -c "import json;print(json.load(open('vendor/fruit-fly-simulation/public/data/manifest.json'))['sources'][0]['url'])")
ANN_SHA=$(python3 -c "import json;print(json.load(open('vendor/fruit-fly-simulation/public/data/manifest.json'))['sources'][0]['sha256'])")
sri() { python3 -c "import base64,sys;print('sha256-'+base64.b64encode(bytes.fromhex(sys.argv[1])).decode())" "$1"; }
{
  echo "# Generated by scripts/gen-assets.sh — do not edit. Fixed-output fetches for large data assets."
  echo "{ fetchurl }:"
  echo "{"
  echo "  # MaleCNS v1.0 cell annotations (CC BY 4.0); SHA-256 as recorded in Xenova's manifest.json"
  echo "  annotations = fetchurl { name = \"body-annotations-male-cns-v1.0.feather\"; url = \"$ANN_URL\"; hash = \"$(sri "$ANN_SHA")\"; };"
  echo "  # Xenova/fruit-fly-simulation @ $XREV, git-lfs objects under public/"
  echo "  xenova = ["
  git -C vendor/fruit-fly-simulation lfs ls-files -l | awk '$3 ~ /^public\// {print $1, $3}' | sort -k2 | while read -r oid path; do
    echo "    { path = \"$path\"; src = fetchurl { name = \"$(basename "$path")\"; url = \"https://huggingface.co/spaces/Xenova/fruit-fly-simulation/resolve/$XREV/$path\"; hash = \"$(sri "$oid")\"; }; }"
  done
  echo "  ];"
  echo "  # AbijahKaj/fruit-fly-brain @ $AREV, git-lfs objects"
  echo "  abijah = ["
  git -C vendor/fruit-fly-brain lfs ls-files -l | awk '{print $1, $3}' | while read -r oid path; do
    echo "    { path = \"$path\"; src = fetchurl { name = \"$(basename "$path")\"; url = \"https://huggingface.co/AbijahKaj/fruit-fly-brain/resolve/$AREV/$path\"; hash = \"$(sri "$oid")\"; }; }"
  done
  echo "  ];"
  echo "}"
} > nix/assets.nix
echo "wrote nix/assets.nix: $(grep -c fetchurl nix/assets.nix) fetches"
